server:
  port: 8081


spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
    url: "jdbc:postgresql://localhost:5432/surveydb"


  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 100
    mongodb:
      database: surveyDB
      host: localhost
      port: 27017
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true

